/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private LinkedList<Integer> testList;
    private LinkedList<Integer> testList1;
    private LinkedList<Integer> testList2;
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    public void testInsert(){
        testList = new LinkedList<>();
        testList.insert(5);
       assertNotNull(testList);

    }
    @Test
    public void testIsIncludedFalse(){
        testList = new LinkedList<>();
        testList.insert(5);
        assertEquals(false, testList.include(50));
    }

    @Test
    public void testIsIncludedTrue(){
        testList = new LinkedList<>();
        testList.insert(5);
        testList.insert(6);
        assertTrue(testList.include(6));
    }
    @Test
    public void testToString(){
        testList = new LinkedList<>();
        testList.insert(5);
        testList.insert(6);
        assertEquals("{6} -> {5} -> Null", testList.toString());
    }
    @Test
    public void testInsertBefore(){
        testList = new LinkedList<>();
        testList.Append(5);
        testList.Append(6);
        testList.Append(9);
        testList.insertBefore(6, 13);
        testList.insertBefore(5, 16);
        assertEquals("{16} -> {5} -> {13} -> {6} -> {9} -> Null", testList.toString());
    }
    @Test
    public void testInsertAfter(){
        testList = new LinkedList<>();
        testList.Append(5);
        testList.Append(6);
        testList.Append(9);
        testList.insertAfter(6, 13);

        assertEquals("{5} -> {6} -> {13} -> {9} -> Null", testList.toString());
    }
    @Test
    public void  addNodeToTheEnd(){

        testList2 = new LinkedList<>();
        testList2.insert(55);
        testList2.Append(33);
        String output=testList2.toString();
        String expected="{55} -> {33} -> Null";
        assertEquals(expected,output);
    }


}
