/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graphs;

import org.junit.jupiter.api.Test;

import java.util.LinkedHashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void test1(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");
        String expected="Vertex{data='Bob'}[]Vertex{data='Alice'}[]";
        assertEquals(expected,graph.printGraph());
    }

    @Test
    public void test2(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");
        graph.addVertex("Mary");

        graph.addEdge("Bob", "Mary",0);
        graph.addEdge("Bob", "Alice",0);
        String expected="Vertex{data='Bob'}[Vertex{data='Mary'}, Vertex{data='Alice'}]Vertex{data='Alice'}[Vertex{data='Bob'}]Vertex{data='Mary'}[Vertex{data='Bob'}]";
        assertEquals(expected,graph.printGraph());
    }
    @Test
    public void test3(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");
        graph.addVertex("Mary");

        graph.addEdge("Bob", "Mary",0);
        graph.addEdge("Bob", "Alice",0);

        graph.removeVertex("Bob");
        graph.removeEdge("Bob","Alice");
        String expected="Vertex{data='Alice'}[]Vertex{data='Mary'}[]";
        assertEquals(expected,graph.printGraph());
    }

    @Test
    public void test4(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");

        assertNull(graph.getNeighbors("bayan"));
    }
    @Test
    public void test5(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");

        assertEquals(2,graph.size());
    }

    @Test
    public void test6(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.removeVertex("Bob");
        assertEquals(0,graph.size());
    }

    @Test
    public void test7(){
        Graph graph = new Graph();
        assertEquals(0,graph.size());
    }
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Breadth First <<<<<<<<<<<<<<<<<<<<<<<

    @Test
    public void test8() {

        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Mary");
        graph.addVertex("Alice");
        graph.addVertex("Carl");

        graph.addEdge("Alice", "Carl",0);
        graph.addEdge("Bob", "Mary",0);
        graph.addEdge("Bob", "Alice",0);

        Set<String> expected= new LinkedHashSet<>();
        expected.add("Alice");
        expected.add("Carl");
        expected.add("Bob");
        expected.add("Mary");

        assertEquals(expected,graph.bft(graph, "Alice"));

    }

    @Test
    public void test9() {

        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Mary");
        graph.addVertex("Alice");
        graph.addVertex("Carl");

        Set<String> expected=new LinkedHashSet<>();
        expected.add("Alice");
        assertEquals(expected,graph.bft(graph, "Alice"));
    }

    @Test
    public void test10() {

        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Mary");
        graph.addVertex("Alice");
        graph.addVertex("Carl");
        graph.addEdge("Alice", "Carl",0);
        graph.addEdge("Bob", "Mary",0);
        Set<String> expected=new LinkedHashSet<>();
        expected.add("Alice");
        expected.add("Carl");
        assertEquals(expected,graph.bft(graph, "Alice"));
    }
    @Test
    public void test11() {
        Graph graph = new Graph();
        Graph graph2 = new Graph();


        Vertex node = graph.addVertex("Pandora");
        Vertex node1 = graph.addVertex("Arendelle");
        Vertex node2 = graph.addVertex("Metroville");
        Vertex node3 = graph.addVertex("Monstroplolis");
        Vertex node4 = graph.addVertex("Narnia");
        Vertex node5 = graph.addVertex("Naboo");


        graph.addEdgesWithWeight(node,node1,150);
        graph.addEdgesWithWeight(node1,node2,99);
        graph.addEdgesWithWeight(node1,node3,42);
        graph.addEdgesWithWeight(node2,node4,37);
        graph.addEdgesWithWeight(node2,node5,26);
        graph.addEdgesWithWeight(node2,node3,105);
        graph.addEdgesWithWeight(node3,node5,73);
        graph.addEdgesWithWeight(node4,node5,250);


        String[] cityNames1 = {"Arendelle", "Monstroplolis", "Naboo"};
        String[] cityNames2 = {"Naboo", "Pandora"};
        String[] cityNames3 = {"Narnia", "Arendelle", "Naboo"};



        assertEquals(115,graph2.businessTrip(graph,cityNames1));
        assertEquals(0,graph2.businessTrip(graph,cityNames2));
        assertEquals(0,graph2.businessTrip(graph,cityNames3));
    }
    //    >>>>>>>>>>>>>>>graph-depth-first<<<<<<<<<<<<<<<<<<<><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

    @Test
    public void test12() {

        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Mary");
        graph.addVertex("Alice");
        graph.addVertex("Carl");

        graph.addEdge("Alice", "Carl",0);
        graph.addEdge("Bob", "Mary",0);
        graph.addEdge("Bob", "Alice",0);

        Set<String> expected= new LinkedHashSet<>();
        expected.add("Alice");
        expected.add("Bob");
        expected.add("Mary");
        expected.add("Carl");

        assertEquals(expected,graph.dft(graph, "Alice"));

    }

    @Test
    public void test13() {

        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Mary");
        graph.addVertex("Alice");
        graph.addVertex("Carl");

        Set<String> expected=new LinkedHashSet<>();
        expected.add("Alice");
        assertEquals(expected,graph.dft(graph, "Alice"));
    }

    @Test
    public void test14() {

        Graph graph = new Graph();

        graph.addVertex("Bob");
        graph.addVertex("Mary");
        graph.addVertex("Alice");
        graph.addVertex("Carl");
        graph.addEdge("Alice", "Carl",0);
        graph.addEdge("Bob", "Mary",0);
        Set<String> expected=new LinkedHashSet<>();
        expected.add("Alice");
        expected.add("Carl");
        assertEquals(expected,graph.dft(graph, "Alice"));
    }
    @Test
    public void test15() {

        Interview g = new Interview(4);
        g.addEdge(0, 1);
        g.addEdge(0, 2);
        g.addEdge(1, 2);
        g.addEdge(2, 0);
        g.addEdge(2, 3);
        g.addEdge(3, 3);


        assertTrue(g.isReachable(1, 3));
        assertFalse(g.isReachable(3, 1));


    }



}
