/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graphs;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
    public void test1(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");
        String expected="Vertex{label='Bob'}[]Vertex{label='Alice'}[]";
        assertEquals(expected,graph.printGraph());
    }

    @Test
    public void test2(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");
        graph.addVertex("Mary");

        graph.addEdge("Bob", "Mary");
        graph.addEdge("Bob", "Alice");
        String expected="Vertex{label='Bob'}[Vertex{label='Mary'}, Vertex{label='Alice'}]Vertex{label='Alice'}[Vertex{label='Bob'}]Vertex{label='Mary'}[Vertex{label='Bob'}]";
        assertEquals(expected,graph.printGraph());
    }
    @Test
    public void test3(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");
        graph.addVertex("Mary");

        graph.addEdge("Bob", "Mary");
        graph.addEdge("Bob", "Alice");

        graph.removeVertex("Bob");
        graph.removeEdge("Bob","Alice");
        String expected="Vertex{label='Alice'}[]Vertex{label='Mary'}[]";
        assertEquals(expected,graph.printGraph());
    }

    @Test
    public void test4(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");

        assertNull(graph.getNeighbors("bayan"));
    }
    @Test
    public void test5(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.addVertex("Alice");

        assertEquals(2,graph.size());
    }

    @Test
    public void test6(){
        Graph graph = new Graph();
        graph.addVertex("Bob");
        graph.removeVertex("Bob");
        assertEquals(0,graph.size());
    }

    @Test
    public void test7(){
        Graph graph = new Graph();
        assertEquals(0,graph.size());
    }

}
