/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    int[] intArray = new int[]{ 8,4,23,24,16};
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    void InsertionSortTest(){

        Sort sort =new Sort();
        sort.InsertionSort(intArray);
        String str ="";
        for (int num: intArray) {
            str+=num+",";
        }
        assertEquals("4,8,16,23,24,",str);
    }
    @Test
    void mergeSortTest(){

        Sort sort =new Sort();
        sort.mergeSort(intArray,intArray.length);
        String str ="";
        for (int num: intArray) {
            str+=num+",";
        }
        assertEquals("4,8,16,23,24,",str);
    }
    @Test
    void quickSortTest(){

        Sort sort =new Sort();
        sort.quickSort(intArray,0,intArray.length-1);
        String str ="";
        for (int num: intArray) {
            str+=num+",";
        }
        assertEquals("4,8,16,23,24,",str);
    }


}
