/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

import org.junit.jupiter.api.Test;

import java.util.Objects;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
    public void addTest(){
        HashTable<String, Integer> hashTable = new HashTable<String, Integer>();
        hashTable.add("Hashem",55);
        hashTable.add("Smadi",66);

        assertNotNull(hashTable.contains("Hashem"));
        assertTrue(hashTable.contains("Hashem"));
        assertEquals(55, hashTable.get("Hashem"));
        assertNull(hashTable.get("Ali"));
    }
    @Test
    public void setOfKeyTest(){
        HashTable hashTable =new HashTable<>();
        hashTable.add("h",1);
        hashTable.add("a",2);
        hashTable.add("s",3);
        assertEquals(3,hashTable.getSize());
    }

    @Test
    public void containTest(){
        System.out.println(Objects.hashCode("FB"));
        System.out.println(Objects.hashCode("Ea"));

        HashTable<String, Integer> hashTable = new HashTable<String, Integer>();
        hashTable.add("Hashem",55);
        hashTable.add("Smadi",66);
        hashTable.add("FB",10);
        hashTable.add("Ea",20);

        assertTrue(hashTable.contains("FB"));
        assertTrue(hashTable.contains("Ea"));

        assertEquals(10, hashTable.get("FB"));
        assertEquals(20, hashTable.get("Ea"));

    }
}
