/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        HashTable hashTable =new HashTable<>();
        hashTable.add("h",1);
        hashTable.add("a",2);
        hashTable.add("s",3);
        System.out.println(hashTable.keySet());

    }
}
