/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interviews;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
    void anagramStringTest (){
        AnagramString anagramString= new AnagramString();
        assertTrue(anagramString.isAnagram("Twelve plus one","Eleven plus two"));
        assertTrue(anagramString.isAnagram("Clint Eastwood","Clint Eastwood"));
        assertTrue(anagramString.isAnagram("Astronomers","Moon starers"));
        assertFalse(anagramString.isAnagram("Software","Swear often"));
    }
}
